### PR TITLE
Lint command

### PR DESCRIPTION
**Pull request by rugabarbo**
It can check one or all packages for compliance with PSR2 standard. There is [CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) under the hood.

### CODE REVIEW

**Comment by samdark** [comment]
Not sure it's good addition. There's [StyleCI](https://styleci.io/) deployed to all repositories so it will automatically fix code style.

**Comment by rugabarbo** [comment]
@samdark StyleCI is useful for the owner of the repository.
`lint` command is useful for the contributor. 

They check the same things, but they are needed at different stages of development. How can I check with StyleCI my code before submitting it for review? So...

**Comment by samdark** [comment]
StyleCI isn't just checking. It's fixing code to be styled as PSR-2 automatically so there's no need to check that.

**Comment by rugabarbo** [comment]
How can I check the code in packages before sending PR? For example, I'm beginner and I need this to learn PSR2 standard and write code according to it.

**Comment by samdark** [comment]
OK. That's maybe a fine case.

**Comment by samdark** [comment]
Let's have it. Thanks!

**Comment by rugabarbo** [comment]
Try it yourself, you'll like it :) There are a lot of interesting things in the packages 😄

**Comment by samdark** [comment]
Oh. Is it possible to switch it to PSR-12?

**Comment by rugabarbo** [comment]
If you just want to try, you can change it temporarily here: https://github.com/yiisoft/yii-dev-tool/blob/91f227f226a23f156d82a5e2c4811a8d5a9d0c08/components/package/PackageManager.php#L333

If you want to change this permanently or make it optional, then I can send a PR. 

What exactly is it about? Will we use standard A constantly? :)

**Pull request merged**
